.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:pySVModel-github| image:: https://img.shields.io/badge/edaa--org-pySystemVerilogModel-323131?logo=github&longCache=true
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel
.. |SHIELD:png:pySVModel-github| image:: https://raster.shields.io/badge/edaa--org-pySystemVerilogModel-323131?logo=github&longCache=true
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel

.. # Sourcecode license
.. |SHIELD:svg:pySVModel-src-license| image:: https://img.shields.io/pypi/l/pySystemVerilogModel?logo=GitHub&label=code%20license
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:png:pySVModel-src-license| image:: https://img.shields.io/pypi/l/pySystemVerilogModel?logo=GitHub&label=code%20license
   :alt: Code license
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:pySVModel-tag| image:: https://img.shields.io/github/v/tag/edaa-org/pySystemVerilogModel?logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/tags
.. |SHIELD:png:pySVModel-tag| image:: https://raster.shields.io/github/v/tag/edaa-org/pySystemVerilogModel?logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/tags

.. # GitHub release
.. |SHIELD:svg:pySVModel-release| image:: https://img.shields.io/github/v/release/edaa-org/pySystemVerilogModel?logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/releases/latest
.. |SHIELD:png:pySVModel-release| image:: https://raster.shields.io/github/v/release/edaa-org/pySystemVerilogModel?logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/releases/latest

.. # GitHub release date
.. |SHIELD:svg:pySVModel-date| image:: https://img.shields.io/github/release-date/edaa-org/pySystemVerilogModel?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/releases
.. |SHIELD:png:pySVModel-date| image:: https://raster.shields.io/github/release-date/edaa-org/pySystemVerilogModel?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:pySVModel-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pySystemVerilogModel
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/network/dependents
.. |SHIELD:png:pySVModel-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pySystemVerilogModel
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:pySVModel-gha-test| image:: https://img.shields.io/github/workflow/status/edaa-org/pySystemVerilogModel/Test%20and%20Coverage?label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/actions?query=workflow%3A%22Test+and+Coverage%22
.. |SHIELD:png:pySVModel-gha-test| image:: https://img.shields.io/github/workflow/status/edaa-org/pySystemVerilogModel/Test%20and%20Coverage?label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/actions?query=workflow%3A%22Test+and+Coverage%22

.. # Codacy - quality
.. |SHIELD:svg:pySVModel-codacy-quality| image:: https://img.shields.io/codacy/grade/39d312bf98244961975559f141c3e000?logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/edaa-org/pySystemVerilogModel
.. |SHIELD:png:pySVModel-codacy-quality| image:: https://raster.shields.io/codacy/grade/39d312bf98244961975559f141c3e000?logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/manual/edaa-org/pySystemVerilogModel

.. # Codacy - coverage
.. |SHIELD:svg:pySVModel-codacy-coverage| image:: https://img.shields.io/codacy/coverage/39d312bf98244961975559f141c3e000?logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/edaa-org/pySystemVerilogModel
.. |SHIELD:png:pySVModel-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/39d312bf98244961975559f141c3e000?logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/manual/edaa-org/pySystemVerilogModel

.. # Codecov - coverage
.. |SHIELD:svg:pySVModel-codecov-coverage| image:: https://img.shields.io/codecov/c/github/edaa-org/pySystemVerilogModel
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pySystemVerilogModel
.. |SHIELD:png:pySVModel-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/edaa-org/pySystemVerilogModel
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pySystemVerilogModel

.. # Libraries - source rank
.. |SHIELD:svg:pySVModel-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pySystemVerilogModel
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySystemVerilogModel/sourcerank
.. |SHIELD:png:pySVModel-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pySystemVerilogModel
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySystemVerilogModel/sourcerank

.. # GHA release
.. |SHIELD:svg:pySVModel-gha-release| image:: https://img.shields.io/github/workflow/status/edaa-org/pySystemVerilogModel/Release?label=release&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Release Status
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/actions?query=workflow%3A%22Release%22
.. |SHIELD:png:pySVModel-gha-release| image:: https://img.shields.io/github/workflow/status/edaa-org/pySystemVerilogModel/Release?label=release&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Release Status
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/actions?query=workflow%3A%22Release%22

.. # PyPI tag
.. |SHIELD:svg:pySVModel-pypi-tag| image:: https://img.shields.io/pypi/v/pySystemVerilogModel?logo=PyPI
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pySystemVerilogModel/
.. |SHIELD:png:pySVModel-pypi-tag| image:: https://raster.shields.io/pypi/v/pySystemVerilogModel?logo=PyPI
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pySystemVerilogModel/

.. # PyPI project status
.. |SHIELD:svg:pySVModel-pypi-status| image:: https://img.shields.io/pypi/status/pySystemVerilogModel?logo=PyPI
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:pySVModel-pypi-status| image:: https://raster.shields.io/pypi/status/pySystemVerilogModel?logo=PyPI
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:pySVModel-pypi-python| image:: https://img.shields.io/pypi/pyversions/pySystemVerilogModel?logo=PyPI
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:pySVModel-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pySystemVerilogModel?logo=PyPI
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:pySVModel-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pySystemVerilogModel
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySystemVerilogModel
.. |SHIELD:png:pySVModel-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pySystemVerilogModel
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySystemVerilogModel

.. # Requires - status
.. |SHIELD:svg:pySVModel-req-status| image:: https://img.shields.io/requires/github/edaa-org/pySystemVerilogModel
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pySystemVerilogModel/requirements/?branch=main
.. |SHIELD:png:pySVModel-req-status| image:: https://raster.shields.io/requires/github/edaa-org/pySystemVerilogModel
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pySystemVerilogModel/requirements/?branch=main

.. # GHA - documentation
.. |SHIELD:svg:pySVModel-gha-doc| image:: https://img.shields.io/github/workflow/status/edaa-org/pySystemVerilogModel/Documentation?label=Documentation&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Documentation Status
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/actions?query=workflow%3A%22Documentation%22
.. |SHIELD:png:pySVModel-gha-doc| image:: https://img.shields.io/github/workflow/status/edaa-org/pySystemVerilogModel/Documentation?label=Documentation&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Documentation Status
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/actions?query=workflow%3A%22Documentation%22

.. # Documentation license
.. |SHIELD:svg:pySVModel-doc-license| image:: https://img.shields.io/badge/doc%20license-CC--BY%204.0-green
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:pySVModel-doc-license| image:: https://img.shields.io/badge/doc%20license-CC--BY%204.0-green
   :alt: Documentation License
   :height: 22
   :target: https://github.com/edaa-org/pySystemVerilogModel/blob/main/doc/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:pySVModel-ghp-doc| image:: https://img.shields.io/badge/doc-read%20now%20%E2%9E%94-blueviolet
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pySystemVerilogModel/
.. |SHIELD:png:pySVModel-ghp-doc| image:: https://img.shields.io/badge/doc-read%20now%20%E2%9E%94-blueviolet
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pySystemVerilogModel/
