.. # Use http://b64.io/ to encode any image to base64. Then replace `/` with
   # `%2F` and `+` with `%2B` (or use http://meyerweb.com/eric/tools/dencoder/).
   # Beware that `?logo=data:image/png;base64,` must also be converted to
   # percent encoding so that the URL is properly parsed.

.. # Sourcecode link to GitHub
.. |SHIELD:svg:pySVModel-github| image:: https://img.shields.io/badge/pyEDAA-pySVModel-29b6f6.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=0277bd
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/edaa-org/pySVModel
.. |SHIELD:png:pySVModel-github| image:: https://raster.shields.io/badge/pyEDAA-pySVModel-29b6f6.svg?longCache=true&style=flat-square&logo=GitHub&labelColor=0277bd
   :alt: Sourcecode on GitHub
   :height: 22
   :target: https://github.com/edaa-org/pySVModel

.. # Sourcecode license
.. |SHIELD:svg:pySVModel-src-license| image:: https://img.shields.io/pypi/l/pySVModel?longCache=true&style=flat-square&logo=Apache&label=code%20license
   :alt: Code license
   :height: 22
   :target: Code-License.html
.. |SHIELD:png:pySVModel-src-license| image:: https://img.shields.io/pypi/l/pySVModel?longCache=true&style=flat-square&logo=Apache&label=code%20license
   :alt: Code license
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/blob/main/LICENSE.md

.. # GitHub tag
.. |SHIELD:svg:pySVModel-tag| image:: https://img.shields.io/github/v/tag/edaa-org/pySVModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/tags
.. |SHIELD:png:pySVModel-tag| image:: https://raster.shields.io/github/v/tag/edaa-org/pySVModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub tag (latest SemVer incl. pre-release
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/tags

.. # GitHub release
.. |SHIELD:svg:pySVModel-release| image:: https://img.shields.io/github/v/release/edaa-org/pySVModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/releases/latest
.. |SHIELD:png:pySVModel-release| image:: https://raster.shields.io/github/v/release/edaa-org/pySVModel?longCache=true&style=flat-square&logo=GitHub&include_prereleases
   :alt: GitHub release (latest SemVer incl. including pre-releases
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/releases/latest

.. # GitHub release date
.. |SHIELD:svg:pySVModel-date| image:: https://img.shields.io/github/release-date/edaa-org/pySVModel?longCache=true&style=flat-square&logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/releases
.. |SHIELD:png:pySVModel-date| image:: https://raster.shields.io/github/release-date/edaa-org/pySVModel?logo=GitHub
   :alt: GitHub release date
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/releases

.. # GitHub/Libraries dependent projects
.. |SHIELD:svg:pySVModel-lib-dep| image:: https://img.shields.io/librariesio/dependent-repos/pypi/pySVModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/network/dependents
.. |SHIELD:png:pySVModel-lib-dep| image:: https://raster.shields.io/librariesio/dependent-repos/pypi/pySVModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Dependent repos (via libraries.io)
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/network/dependents

.. # GHA test and coverage
.. |SHIELD:svg:pySVModel-gha-test| image:: https://img.shields.io/github/workflow/status/edaa-org/pySVModel/Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish/main?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/actions?query=workflow%3A%22Test+and+Coverage%22
.. |SHIELD:png:pySVModel-gha-test| image:: https://img.shields.io/github/workflow/status/edaa-org/pySVModel/Unit%20Testing,%20Coverage%20Collection,%20Package,%20Release,%20Documentation%20and%20Publish/main?longCache=true&style=flat-square&label=Build%20and%20Test&logo=GitHub%20Actions&logoColor=FFFFFF
   :alt: GitHub Workflow - Build and Test Status
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/actions?query=workflow%3A%22Test+and+Coverage%22

.. # Codacy - quality
.. |SHIELD:svg:pySVModel-codacy-quality| image:: https://img.shields.io/codacy/grade/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pySVModel
.. |SHIELD:png:pySVModel-codacy-quality| image:: https://raster.shields.io/codacy/grade/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Quality
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pySVModel

.. # Codacy - coverage
.. |SHIELD:svg:pySVModel-codacy-coverage| image:: https://img.shields.io/codacy/coverage/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pySVModel
.. |SHIELD:png:pySVModel-codacy-coverage| image:: https://raster.shields.io/codacy/coverage/39d312bf98244961975559f141c3e000?longCache=true&style=flat-square&logo=codacy
   :alt: Codacy - Line Coverage
   :height: 22
   :target: https://www.codacy.com/gh/edaa-org/pySVModel

.. # Codecov - coverage
.. |SHIELD:svg:pySVModel-codecov-coverage| image:: https://img.shields.io/codecov/c/github/edaa-org/pySVModel?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pySVModel
.. |SHIELD:png:pySVModel-codecov-coverage| image:: https://raster.shields.io/codecov/c/github/edaa-org/pySVModel?longCache=true&style=flat-square&logo=Codecov
   :alt: Codecov - Branch Coverage
   :height: 22
   :target: https://codecov.io/gh/edaa-org/pySVModel

.. # Libraries - source rank
.. |SHIELD:svg:pySVModel-lib-rank| image:: https://img.shields.io/librariesio/sourcerank/pypi/pySVModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySVModel/sourcerank
.. |SHIELD:png:pySVModel-lib-rank| image:: https://raster.shields.io/librariesio/sourcerank/pypi/pySVModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io SourceRank
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySVModel/sourcerank

.. # PyPI tag
.. |SHIELD:svg:pySVModel-pypi-tag| image:: https://img.shields.io/pypi/v/pySVModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pySVModel/
.. |SHIELD:png:pySVModel-pypi-tag| image:: https://raster.shields.io/pypi/v/pySVModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Tag
   :height: 22
   :target: https://pypi.org/project/pySVModel/

.. # PyPI project status
.. |SHIELD:svg:pySVModel-pypi-status| image:: https://img.shields.io/pypi/status/pySVModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22
.. |SHIELD:png:pySVModel-pypi-status| image:: https://raster.shields.io/pypi/status/pySVModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Status
   :height: 22

.. # PyPI Python versions
.. |SHIELD:svg:pySVModel-pypi-python| image:: https://img.shields.io/pypi/pyversions/pySVModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22
.. |SHIELD:png:pySVModel-pypi-python| image:: https://raster.shields.io/pypi/pyversions/pySVModel?longCache=true&style=flat-square&logo=PyPI&logoColor=FBE072
   :alt: PyPI - Python Version
   :height: 22

.. # Libraries - status
.. |SHIELD:svg:pySVModel-lib-status| image:: https://img.shields.io/librariesio/release/pypi/pySVModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySVModel
.. |SHIELD:png:pySVModel-lib-status| image:: https://raster.shields.io/librariesio/release/pypi/pySVModel?longCache=true&style=flat-square&logo=Libraries.io&logoColor=fff
   :alt: Libraries.io status for latest release
   :height: 22
   :target: https://libraries.io/github/edaa-org/pySVModel

.. # Requires - status
.. |SHIELD:svg:pySVModel-req-status| image:: https://img.shields.io/requires/github/edaa-org/pySVModel?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pySVModel/requirements/?branch=main
.. |SHIELD:png:pySVModel-req-status| image:: https://raster.shields.io/requires/github/edaa-org/pySVModel?longCache=true&style=flat-square
   :alt: Requires.io
   :height: 22
   :target: https://requires.io/github/edaa-org/pySVModel/requirements/?branch=main

.. # Documentation license
.. |SHIELD:svg:pySVModel-doc-license| image:: https://img.shields.io/badge/doc%20license-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: Doc-License.html
.. |SHIELD:png:pySVModel-doc-license| image:: https://raster.shields.io/badge/doc%20license-CC--BY%204.0-green?longCache=true&style=flat-square&logo=CreativeCommons&logoColor=fff
   :alt: Documentation License
   :height: 22
   :target: https://github.com/edaa-org/pySVModel/blob/main/doc/Doc-License.rst

.. # GHPages - read now
.. |SHIELD:svg:pySVModel-ghp-doc| image:: https://img.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpySVModel&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpySVModel%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pySVModel/
.. |SHIELD:png:pySVModel-ghp-doc| image:: https://raster.shields.io/website?longCache=true&style=flat-square&label=edaa-org.github.io%2FpySVModel&logo=GitHub&logoColor=fff&up_color=blueviolet&up_message=Read%20now%20%E2%9E%9A&url=https%3A%2F%2Fedaa-org.github.io%2FpySVModel%2Findex.html
   :alt: Documentation - Read Now!
   :height: 22
   :target: https://edaa-org.github.io/pySVModel/
